export const members = [
    {
        "Tid":"1234",
        "fname":"Varoodhini",
        "lname":"kamughanti",
        "DOB":"22-08-1986",
        "POD":"Warangal",
        "TOB":"23:00",
        "Age":"31",
        "sex":"Female",
        "Caste":"Brahmin",
        "Sub-Caste":"Vadiki",
        "Star":"Tula",
        "Raasi":"Poorvabadhra",
        "Education":"Btech",
        "Occupation":"S/w Eng",
        "Comapny":"Self",
        "Package":"4 LPA",
        "House":"Own appt",
        "Vehicle":"Car",
        "Preferences":"Guy",
        "discovery":"yes",
        "Fb":"no",
        img:["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe4anQLy4QyWZr_AuiNwIExGhDYQsj2_3R1q2fabbWjppYbKPt",""]
    },
    {
        "Tid":"2345",
        "fname":"Karoodhini",
        "lname":"Vamughanti",
        "DOB":"22-08-1986",
        "POD":"Warangal",
        "TOB":"23:00",
        "Age":"21",
        "sex":"Female",
        "Caste":"Brahmin",
        "Sub-Caste":"Vadiki",
        "Star":"Tula",
        "Raasi":"Poorvabadhra",
        "Education":"Btech",
        "Occupation":"S/w Eng",
        "Comapny":"Self",
        "Package":"4 LPA",
        "House":"Own appt",
        "Vehicle":"Car",
        "Preferences":"Guy",
        "discovery":"yes",
        "Fb":"no",
        "img":["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe4anQLy4QyWZr_AuiNwIExGhDYQsj2_3R1q2fabbWjppYbKPt",""]
    },
    {
        "Tid":"3456",
        "fname":"Daroodhini",
        "lname":"Ramughanti",
        "DOB":"22-08-1986",
        "POD":"Warangal",
        "TOB":"23:00",
        "Age":"21",
        "sex":"Female",
        "Caste":"Brahmin",
        "Sub-Caste":"Vadiki",
        "Star":"Tula",
        "Raasi":"Poorvabadhra",
        "Education":"Btech",
        "Occupation":"S/w Eng",
        "Comapny":"Self",
        "Package":"4 LPA",
        "House":"Own appt",
        "Vehicle":"Car",
        "Preferences":"Guy",
        "discovery":"yes",
        "Fb":"no",
        "img":["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe4anQLy4QyWZr_AuiNwIExGhDYQsj2_3R1q2fabbWjppYbKPt",""]
    },
    {
        "Tid":"4567",
        "fname":"Raroodhini",
        "lname":"Damughanti",
        "DOB":"22-08-1986",
        "POD":"Warangal",
        "TOB":"23:00",
        "Age":"21",
        "sex":"Female",
        "Caste":"Brahmin",
        "Sub-Caste":"Vadiki",
        "Star":"Tula",
        "Raasi":"Poorvabadhra",
        "Education":"Btech",
        "Occupation":"S/w Eng",
        "Comapny":"Self",
        "Package":"4 LPA",
        "House":"Own appt",
        "Vehicle":"Car",
        "Preferences":"Guy",
        "discovery":"yes",
        "Fb":"no",
        "img":["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe4anQLy4QyWZr_AuiNwIExGhDYQsj2_3R1q2fabbWjppYbKPt",""]
    }
];